/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`src/__tests__/api.test.ts TAP isSearchMatch_Branded > isSearchMatch_Branded 1`] = `
Object {
  "currentPage": 1,
  "foods": Array [
    Object {
      "allHighlightFields": "<b>Brand Owner</b>: Elmhurst <em>Milk</em> & Cream Co.Inc.<br/><b>Ingredients</b>: REDUCED FAT <em>MILK</em>, VITAMIN A PALMITATE, VITAMIN D3. ",
      "brandOwner": "Elmhurst Milk & Cream Co.Inc.",
      "dataType": "Branded",
      "description": "MILK",
      "fdcId": 1909132,
      "foodNutrients": Array [
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1003,
          "nutrientName": "Protein",
          "nutrientNumber": "203",
          "unitName": "G",
          "value": 3.39,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1004,
          "nutrientName": "Total lipid (fat)",
          "nutrientNumber": "204",
          "unitName": "G",
          "value": 2.12,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1005,
          "nutrientName": "Carbohydrate, by difference",
          "nutrientNumber": "205",
          "unitName": "G",
          "value": 5.08,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1008,
          "nutrientName": "Energy",
          "nutrientNumber": "208",
          "unitName": "KCAL",
          "value": 55,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 2000,
          "nutrientName": "Sugars, total including NLEA",
          "nutrientNumber": "269",
          "unitName": "G",
          "value": 5.08,
        },
        Object {
          "derivationCode": "LCCD",
          "derivationDescription": "Calculated from a daily value percentage per serving size measure",
          "nutrientId": 1079,
          "nutrientName": "Fiber, total dietary",
          "nutrientNumber": "291",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "LCCD",
          "derivationDescription": "Calculated from a daily value percentage per serving size measure",
          "nutrientId": 1087,
          "nutrientName": "Calcium, Ca",
          "nutrientNumber": "301",
          "unitName": "MG",
          "value": 127,
        },
        Object {
          "derivationCode": "LCCD",
          "derivationDescription": "Calculated from a daily value percentage per serving size measure",
          "nutrientId": 1089,
          "nutrientName": "Iron, Fe",
          "nutrientNumber": "303",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1093,
          "nutrientName": "Sodium, Na",
          "nutrientNumber": "307",
          "unitName": "MG",
          "value": 55,
        },
        Object {
          "derivationCode": "LCCD",
          "derivationDescription": "Calculated from a daily value percentage per serving size measure",
          "nutrientId": 1104,
          "nutrientName": "Vitamin A, IU",
          "nutrientNumber": "318",
          "unitName": "IU",
          "value": 212,
        },
        Object {
          "derivationCode": "LCCD",
          "derivationDescription": "Calculated from a daily value percentage per serving size measure",
          "nutrientId": 1110,
          "nutrientName": "Vitamin D (D2 + D3), International Units",
          "nutrientNumber": "324",
          "unitName": "IU",
          "value": 42,
        },
        Object {
          "derivationCode": "LCCD",
          "derivationDescription": "Calculated from a daily value percentage per serving size measure",
          "nutrientId": 1162,
          "nutrientName": "Vitamin C, total ascorbic acid",
          "nutrientNumber": "401",
          "unitName": "MG",
          "value": 1,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1253,
          "nutrientName": "Cholesterol",
          "nutrientNumber": "601",
          "unitName": "MG",
          "value": 8,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1257,
          "nutrientName": "Fatty acids, total trans",
          "nutrientNumber": "605",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "LCCS",
          "derivationDescription": "Calculated from value per serving size measure",
          "nutrientId": 1258,
          "nutrientName": "Fatty acids, total saturated",
          "nutrientNumber": "606",
          "unitName": "G",
          "value": 1.27,
        },
      ],
      "gtinUpc": "072050301314",
      "ingredients": "REDUCED FAT MILK, VITAMIN A PALMITATE, VITAMIN D3. ",
      "publishedDate": "2021-07-29",
      "score": 750.2554,
      "servingSize": 236,
    },
  ],
  "foodSearchCriteria": Object {
    "dataType": Array [
      "Branded",
    ],
    "endDate": "2023-01-01",
    "pageNumber": 1,
    "pageSize": 1,
    "query": "milk",
    "requireAllWords": false,
    "startDate": "2019-01-01",
  },
  "totalHits": 103547,
  "totalPages": 103547,
}
`

exports[`src/__tests__/api.test.ts TAP isSearchMatch_Foundation > isSearchMatch_Foundation 1`] = `
Object {
  "currentPage": 1,
  "foods": Array [
    Object {
      "additionalDescriptions": "",
      "allHighlightFields": "",
      "dataType": "Foundation",
      "description": "Cheese, ricotta, whole milk",
      "fdcId": 746766,
      "foodNutrients": Array [
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1253,
          "nutrientName": "Cholesterol",
          "nutrientNumber": "601",
          "unitName": "MG",
          "value": 48,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1257,
          "nutrientName": "Fatty acids, total trans",
          "nutrientNumber": "605",
          "unitName": "G",
          "value": 0.351,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1258,
          "nutrientName": "Fatty acids, total saturated",
          "nutrientNumber": "606",
          "unitName": "G",
          "value": 6.97,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1261,
          "nutrientName": "SFA 8:0",
          "nutrientNumber": "609",
          "unitName": "G",
          "value": 0.125,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1263,
          "nutrientName": "SFA 12:0",
          "nutrientNumber": "611",
          "unitName": "G",
          "value": 0.36,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1264,
          "nutrientName": "SFA 14:0",
          "nutrientNumber": "612",
          "unitName": "G",
          "value": 1.15,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1272,
          "nutrientName": "PUFA 22:6 n-3 (DHA)",
          "nutrientNumber": "621",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1273,
          "nutrientName": "SFA 22:0",
          "nutrientNumber": "624",
          "unitName": "G",
          "value": 0.006,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1278,
          "nutrientName": "PUFA 20:5 n-3 (EPA)",
          "nutrientNumber": "629",
          "unitName": "G",
          "value": 0.005,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1280,
          "nutrientName": "PUFA 22:5 n-3 (DPA)",
          "nutrientNumber": "631",
          "unitName": "G",
          "value": 0.007,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1300,
          "nutrientName": "SFA 17:0",
          "nutrientNumber": "653",
          "unitName": "G",
          "value": 0.067,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1301,
          "nutrientName": "SFA 24:0",
          "nutrientNumber": "654",
          "unitName": "G",
          "value": 0.004,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1303,
          "nutrientName": "TFA 16:1 t",
          "nutrientNumber": "662",
          "unitName": "G",
          "value": 0.032,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1312,
          "nutrientName": "MUFA 24:1 c",
          "nutrientNumber": "671",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1315,
          "nutrientName": "MUFA 18:1 c",
          "nutrientNumber": "674",
          "unitName": "G",
          "value": 2.22,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1316,
          "nutrientName": "PUFA 18:2 n-6 c,c",
          "nutrientNumber": "675",
          "unitName": "G",
          "value": 0.259,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1317,
          "nutrientName": "MUFA 22:1 c",
          "nutrientNumber": "676",
          "unitName": "G",
          "value": 0.002,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1323,
          "nutrientName": "MUFA 17:1",
          "nutrientNumber": "687",
          "unitName": "G",
          "value": 0.021,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1329,
          "nutrientName": "Fatty acids, total trans-monoenoic",
          "nutrientNumber": "693",
          "unitName": "G",
          "value": 0.283,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1333,
          "nutrientName": "MUFA 15:1",
          "nutrientNumber": "697",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1404,
          "nutrientName": "PUFA 18:3 n-3 c,c,c (ALA)",
          "nutrientNumber": "851",
          "unitName": "G",
          "value": 0.042,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1405,
          "nutrientName": "PUFA 20:3 n-3",
          "nutrientNumber": "852",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1411,
          "nutrientName": "PUFA 22:4",
          "nutrientNumber": "858",
          "unitName": "G",
          "value": 0.003,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1166,
          "nutrientName": "Riboflavin",
          "nutrientNumber": "405",
          "unitName": "MG",
          "value": 0.327,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1177,
          "nutrientName": "Folate, total",
          "nutrientNumber": "417",
          "unitName": "UG",
          "value": 4,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1178,
          "nutrientName": "Vitamin B-12",
          "nutrientNumber": "418",
          "unitName": "UG",
          "value": 0.78,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1228,
          "nutrientName": "Hydroxyproline",
          "nutrientNumber": "521",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1101,
          "nutrientName": "Manganese, Mn",
          "nutrientNumber": "315",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1003,
          "nutrientName": "Protein",
          "nutrientNumber": "203",
          "unitName": "G",
          "value": 7.81,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1007,
          "nutrientName": "Ash",
          "nutrientNumber": "207",
          "unitName": "G",
          "value": 1.36,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1089,
          "nutrientName": "Iron, Fe",
          "nutrientNumber": "303",
          "unitName": "MG",
          "value": 0.1,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1090,
          "nutrientName": "Magnesium, Mg",
          "nutrientNumber": "304",
          "unitName": "MG",
          "value": 19.7,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1091,
          "nutrientName": "Phosphorus, P",
          "nutrientNumber": "305",
          "unitName": "MG",
          "value": 162,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1093,
          "nutrientName": "Sodium, Na",
          "nutrientNumber": "307",
          "unitName": "MG",
          "value": 105,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1098,
          "nutrientName": "Copper, Cu",
          "nutrientNumber": "312",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1062,
          "nutrientName": "Energy",
          "nutrientNumber": "268",
          "unitName": "kJ",
          "value": 657,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1259,
          "nutrientName": "SFA 4:0",
          "nutrientNumber": "607",
          "unitName": "G",
          "value": 0.251,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1260,
          "nutrientName": "SFA 6:0",
          "nutrientNumber": "608",
          "unitName": "G",
          "value": 0.199,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1262,
          "nutrientName": "SFA 10:0",
          "nutrientNumber": "610",
          "unitName": "G",
          "value": 0.306,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1265,
          "nutrientName": "SFA 16:0",
          "nutrientNumber": "613",
          "unitName": "G",
          "value": 3.36,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1266,
          "nutrientName": "SFA 18:0",
          "nutrientNumber": "614",
          "unitName": "G",
          "value": 1.02,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1267,
          "nutrientName": "SFA 20:0",
          "nutrientNumber": "615",
          "unitName": "G",
          "value": 0.014,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1271,
          "nutrientName": "PUFA 20:4",
          "nutrientNumber": "620",
          "unitName": "G",
          "value": 0.015,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1276,
          "nutrientName": "PUFA 18:4",
          "nutrientNumber": "627",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1292,
          "nutrientName": "Fatty acids, total monounsaturated",
          "nutrientNumber": "645",
          "unitName": "G",
          "value": 2.56,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1293,
          "nutrientName": "Fatty acids, total polyunsaturated",
          "nutrientNumber": "646",
          "unitName": "G",
          "value": 0.389,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1299,
          "nutrientName": "SFA 15:0",
          "nutrientNumber": "652",
          "unitName": "G",
          "value": 0.116,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1304,
          "nutrientName": "TFA 18:1 t",
          "nutrientNumber": "663",
          "unitName": "G",
          "value": 0.251,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1305,
          "nutrientName": "TFA 22:1 t",
          "nutrientNumber": "664",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1306,
          "nutrientName": "TFA 18:2 t not further defined",
          "nutrientNumber": "665",
          "unitName": "G",
          "value": 0.068,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1311,
          "nutrientName": "PUFA 18:2 CLAs",
          "nutrientNumber": "670",
          "unitName": "G",
          "value": 0.049,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1313,
          "nutrientName": "PUFA 20:2 n-6 c,c",
          "nutrientNumber": "672",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1314,
          "nutrientName": "MUFA 16:1 c",
          "nutrientNumber": "673",
          "unitName": "G",
          "value": 0.184,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1321,
          "nutrientName": "PUFA 18:3 n-6 c,c,c",
          "nutrientNumber": "685",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1331,
          "nutrientName": "Fatty acids, total trans-polyenoic",
          "nutrientNumber": "695",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1406,
          "nutrientName": "PUFA 20:4 n-6",
          "nutrientNumber": "853",
          "unitName": "G",
          "value": 0.012,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1087,
          "nutrientName": "Calcium, Ca",
          "nutrientNumber": "301",
          "unitName": "MG",
          "value": 224,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1092,
          "nutrientName": "Potassium, K",
          "nutrientNumber": "306",
          "unitName": "MG",
          "value": 230,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1095,
          "nutrientName": "Zinc, Zn",
          "nutrientNumber": "309",
          "unitName": "MG",
          "value": 0.56,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1103,
          "nutrientName": "Selenium, Se",
          "nutrientNumber": "317",
          "unitName": "UG",
          "value": 5.5,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1167,
          "nutrientName": "Niacin",
          "nutrientNumber": "406",
          "unitName": "MG",
          "value": 0.168,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1170,
          "nutrientName": "Pantothenic acid",
          "nutrientNumber": "410",
          "unitName": "MG",
          "value": 0.673,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1175,
          "nutrientName": "Vitamin B-6",
          "nutrientNumber": "415",
          "unitName": "MG",
          "value": 0.099,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1004,
          "nutrientName": "Total lipid (fat)",
          "nutrientNumber": "204",
          "unitName": "G",
          "value": 11,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1005,
          "nutrientName": "Carbohydrate, by difference",
          "nutrientNumber": "205",
          "unitName": "G",
          "value": 6.86,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1008,
          "nutrientName": "Energy",
          "nutrientNumber": "208",
          "unitName": "KCAL",
          "value": 157,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1051,
          "nutrientName": "Water",
          "nutrientNumber": "255",
          "unitName": "G",
          "value": 72.9,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1165,
          "nutrientName": "Thiamin",
          "nutrientNumber": "404",
          "unitName": "MG",
          "value": 0.043,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1109,
          "nutrientName": "Vitamin E (alpha-tocopherol)",
          "nutrientNumber": "323",
          "unitName": "MG",
          "value": 0.27,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1185,
          "nutrientName": "Vitamin K (phylloquinone)",
          "nutrientNumber": "430",
          "unitName": "UG",
          "value": 0.6,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1335,
          "nutrientName": "SFA 11:0",
          "nutrientNumber": "699",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 2009,
          "nutrientName": "MUFA 14:1 c",
          "nutrientNumber": "822",
          "unitName": "G",
          "value": 0.117,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 2019,
          "nutrientName": "TFA 18:3 t",
          "nutrientNumber": "834",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 2012,
          "nutrientName": "MUFA 20:1 c",
          "nutrientNumber": "829",
          "unitName": "G",
          "value": 0.02,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1414,
          "nutrientName": "PUFA 20:3 n-9",
          "nutrientNumber": "861",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 2014,
          "nutrientName": "MUFA 22:1 n-9",
          "nutrientNumber": "676.1",
          "unitName": "G",
          "value": 0.002,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1334,
          "nutrientName": "PUFA 22:2",
          "nutrientNumber": "698",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1002,
          "nutrientName": "Nitrogen",
          "nutrientNumber": "202",
          "unitName": "G",
          "value": 1.22,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1222,
          "nutrientName": "Alanine",
          "nutrientNumber": "513",
          "unitName": "G",
          "value": 0.325,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1220,
          "nutrientName": "Arginine",
          "nutrientNumber": "511",
          "unitName": "G",
          "value": 0.21,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1223,
          "nutrientName": "Aspartic acid",
          "nutrientNumber": "514",
          "unitName": "G",
          "value": 0.735,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1232,
          "nutrientName": "Cysteine",
          "nutrientNumber": "526",
          "unitName": "G",
          "value": 0.18,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1224,
          "nutrientName": "Glutamic acid",
          "nutrientNumber": "515",
          "unitName": "G",
          "value": 1.3,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1225,
          "nutrientName": "Glycine",
          "nutrientNumber": "516",
          "unitName": "G",
          "value": 0.135,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1221,
          "nutrientName": "Histidine",
          "nutrientNumber": "512",
          "unitName": "G",
          "value": 0.175,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1212,
          "nutrientName": "Isoleucine",
          "nutrientNumber": "503",
          "unitName": "G",
          "value": 0.365,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1213,
          "nutrientName": "Leucine",
          "nutrientNumber": "504",
          "unitName": "G",
          "value": 0.785,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1214,
          "nutrientName": "Lysine",
          "nutrientNumber": "505",
          "unitName": "G",
          "value": 0.655,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1215,
          "nutrientName": "Methionine",
          "nutrientNumber": "506",
          "unitName": "G",
          "value": 0.17,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1217,
          "nutrientName": "Phenylalanine",
          "nutrientNumber": "508",
          "unitName": "G",
          "value": 0.27,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1226,
          "nutrientName": "Proline",
          "nutrientNumber": "517",
          "unitName": "G",
          "value": 0.565,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1227,
          "nutrientName": "Serine",
          "nutrientNumber": "518",
          "unitName": "G",
          "value": 0.365,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1211,
          "nutrientName": "Threonine",
          "nutrientNumber": "502",
          "unitName": "G",
          "value": 0.395,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1210,
          "nutrientName": "Tryptophan",
          "nutrientNumber": "501",
          "unitName": "G",
          "value": 0.115,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1218,
          "nutrientName": "Tyrosine",
          "nutrientNumber": "509",
          "unitName": "G",
          "value": 0.25,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1219,
          "nutrientName": "Valine",
          "nutrientNumber": "510",
          "unitName": "G",
          "value": 0.325,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1128,
          "nutrientName": "Tocotrienol, alpha",
          "nutrientNumber": "344",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1125,
          "nutrientName": "Tocopherol, beta",
          "nutrientNumber": "341",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1129,
          "nutrientName": "Tocotrienol, beta",
          "nutrientNumber": "345",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1127,
          "nutrientName": "Tocopherol, delta",
          "nutrientNumber": "343",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1131,
          "nutrientName": "Tocotrienol, delta",
          "nutrientNumber": "347",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1126,
          "nutrientName": "Tocopherol, gamma",
          "nutrientNumber": "342",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1130,
          "nutrientName": "Tocotrienol, gamma",
          "nutrientNumber": "346",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1184,
          "nutrientName": "Vitamin K (Dihydrophylloquinone)",
          "nutrientNumber": "429",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1183,
          "nutrientName": "Vitamin K (Menaquinone-4)",
          "nutrientNumber": "428",
          "unitName": "UG",
          "value": 3.1,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1330,
          "nutrientName": "Fatty acids, total trans-dienoic",
          "nutrientNumber": "694",
          "unitName": "G",
          "value": 0.068,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2010,
          "nutrientName": "MUFA 17:1 c",
          "nutrientNumber": "825",
          "unitName": "G",
          "value": 0.021,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2016,
          "nutrientName": "PUFA 18:2 c",
          "nutrientNumber": "831",
          "unitName": "G",
          "value": 0.308,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2018,
          "nutrientName": "PUFA 18:3 c",
          "nutrientNumber": "833",
          "unitName": "G",
          "value": 0.042,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2020,
          "nutrientName": "PUFA 20:3 c",
          "nutrientNumber": "835",
          "unitName": "G",
          "value": 0.012,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2022,
          "nutrientName": "PUFA 20:4c",
          "nutrientNumber": "836",
          "unitName": "G",
          "value": 0.015,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2023,
          "nutrientName": "PUFA 20:5c",
          "nutrientNumber": "837",
          "unitName": "G",
          "value": 0.005,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2024,
          "nutrientName": "PUFA 22:5 c",
          "nutrientNumber": "838",
          "unitName": "G",
          "value": 0.007,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2025,
          "nutrientName": "PUFA 22:6 c",
          "nutrientNumber": "839",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 2026,
          "nutrientName": "PUFA 20:2 c",
          "nutrientNumber": "840",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "derivationCode": "AS",
          "derivationDescription": "Summed",
          "nutrientId": 1085,
          "nutrientName": "Total fat (NLEA)",
          "nutrientNumber": "298",
          "unitName": "G",
          "value": 10.3,
        },
        Object {
          "derivationCode": "A",
          "derivationDescription": "Analytical",
          "nutrientId": 1105,
          "nutrientName": "Retinol",
          "nutrientNumber": "319",
          "unitName": "UG",
          "value": 127,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1106,
          "nutrientName": "Vitamin A, RAE",
          "nutrientNumber": "320",
          "unitName": "UG",
          "value": 127,
        },
      ],
      "ndbNumber": 1036,
      "publishedDate": "2019-12-16",
      "score": 197.30545,
      "servingSize": 100,
    },
  ],
  "foodSearchCriteria": Object {
    "dataType": Array [
      "Foundation",
    ],
    "endDate": "2023-01-01",
    "pageNumber": 1,
    "pageSize": 1,
    "query": "milk",
    "requireAllWords": false,
    "startDate": "2019-01-01",
  },
  "totalHits": 13,
  "totalPages": 13,
}
`

exports[`src/__tests__/api.test.ts TAP isSearchMatch_SRLegacy > isSearchMatch_SRLegacy 1`] = `
Object {
  "currentPage": 1,
  "foods": Array [
    Object {
      "additionalDescriptions": "",
      "allHighlightFields": "",
      "dataType": "SR Legacy",
      "description": "Crackers, milk",
      "fdcId": 174980,
      "foodNutrients": Array [
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1104,
          "nutrientName": "Vitamin A, IU",
          "nutrientNumber": "318",
          "unitName": "IU",
          "value": 58,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1105,
          "nutrientName": "Retinol",
          "nutrientNumber": "319",
          "unitName": "UG",
          "value": 16,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1106,
          "nutrientName": "Vitamin A, RAE",
          "nutrientNumber": "320",
          "unitName": "UG",
          "value": 16,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1107,
          "nutrientName": "Carotene, beta",
          "nutrientNumber": "321",
          "unitName": "UG",
          "value": 3,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1108,
          "nutrientName": "Carotene, alpha",
          "nutrientNumber": "322",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1177,
          "nutrientName": "Folate, total",
          "nutrientNumber": "417",
          "unitName": "UG",
          "value": 90,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1185,
          "nutrientName": "Vitamin K (phylloquinone)",
          "nutrientNumber": "430",
          "unitName": "UG",
          "value": 3.8,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1120,
          "nutrientName": "Cryptoxanthin, beta",
          "nutrientNumber": "334",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1122,
          "nutrientName": "Lycopene",
          "nutrientNumber": "337",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1057,
          "nutrientName": "Caffeine",
          "nutrientNumber": "262",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1058,
          "nutrientName": "Theobromine",
          "nutrientNumber": "263",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1109,
          "nutrientName": "Vitamin E (alpha-tocopherol)",
          "nutrientNumber": "323",
          "unitName": "MG",
          "value": 1.22,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1123,
          "nutrientName": "Lutein + zeaxanthin",
          "nutrientNumber": "338",
          "unitName": "UG",
          "value": 16,
        },
        Object {
          "derivationCode": "Z",
          "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
          "nutrientId": 1110,
          "nutrientName": "Vitamin D (D2 + D3), International Units",
          "nutrientNumber": "324",
          "unitName": "IU",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1276,
          "nutrientName": "PUFA 18:4",
          "nutrientNumber": "627",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1280,
          "nutrientName": "PUFA 22:5 n-3 (DPA)",
          "nutrientNumber": "631",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "nutrientId": 1018,
          "nutrientName": "Alcohol, ethyl",
          "nutrientNumber": "221",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "derivationCode": "BFNN",
          "derivationDescription": "Based on another form of the food or similar food; Concentration adjustment; Non-fat solids; Retention factors not used",
          "nutrientId": 1180,
          "nutrientName": "Choline, total",
          "nutrientNumber": "421",
          "unitName": "MG",
          "value": 10.8,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1186,
          "nutrientName": "Folic acid",
          "nutrientNumber": "431",
          "unitName": "UG",
          "value": 70,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1190,
          "nutrientName": "Folate, DFE",
          "nutrientNumber": "435",
          "unitName": "UG",
          "value": 139,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1187,
          "nutrientName": "Folate, food",
          "nutrientNumber": "432",
          "unitName": "UG",
          "value": 20,
        },
        Object {
          "derivationCode": "NR",
          "derivationDescription": "Nutrient that is based on other nutrient/s; value used directly, ex. Nut.#204 from Nut.#298",
          "nutrientId": 1093,
          "nutrientName": "Sodium, Na",
          "nutrientNumber": "307",
          "unitName": "MG",
          "value": 687,
        },
        Object {
          "nutrientId": 1210,
          "nutrientName": "Tryptophan",
          "nutrientNumber": "501",
          "unitName": "G",
          "value": 0.1,
        },
        Object {
          "nutrientId": 1211,
          "nutrientName": "Threonine",
          "nutrientNumber": "502",
          "unitName": "G",
          "value": 0.221,
        },
        Object {
          "nutrientId": 1215,
          "nutrientName": "Methionine",
          "nutrientNumber": "506",
          "unitName": "G",
          "value": 0.138,
        },
        Object {
          "nutrientId": 1217,
          "nutrientName": "Phenylalanine",
          "nutrientNumber": "508",
          "unitName": "G",
          "value": 0.376,
        },
        Object {
          "nutrientId": 1218,
          "nutrientName": "Tyrosine",
          "nutrientNumber": "509",
          "unitName": "G",
          "value": 0.237,
        },
        Object {
          "nutrientId": 1222,
          "nutrientName": "Alanine",
          "nutrientNumber": "513",
          "unitName": "G",
          "value": 0.246,
        },
        Object {
          "nutrientId": 1224,
          "nutrientName": "Glutamic acid",
          "nutrientNumber": "515",
          "unitName": "G",
          "value": 2.48,
        },
        Object {
          "nutrientId": 1225,
          "nutrientName": "Glycine",
          "nutrientNumber": "516",
          "unitName": "G",
          "value": 0.264,
        },
        Object {
          "nutrientId": 1226,
          "nutrientName": "Proline",
          "nutrientNumber": "517",
          "unitName": "G",
          "value": 0.858,
        },
        Object {
          "nutrientId": 1165,
          "nutrientName": "Thiamin",
          "nutrientNumber": "404",
          "unitName": "MG",
          "value": 0.538,
        },
        Object {
          "nutrientId": 1166,
          "nutrientName": "Riboflavin",
          "nutrientNumber": "405",
          "unitName": "MG",
          "value": 0.418,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1272,
          "nutrientName": "PUFA 22:6 n-3 (DHA)",
          "nutrientNumber": "621",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "nutrientId": 1003,
          "nutrientName": "Protein",
          "nutrientNumber": "203",
          "unitName": "G",
          "value": 7.6,
        },
        Object {
          "nutrientId": 1007,
          "nutrientName": "Ash",
          "nutrientNumber": "207",
          "unitName": "G",
          "value": 2.2,
        },
        Object {
          "nutrientId": 1098,
          "nutrientName": "Copper, Cu",
          "nutrientNumber": "312",
          "unitName": "MG",
          "value": 0.227,
        },
        Object {
          "nutrientId": 1101,
          "nutrientName": "Manganese, Mn",
          "nutrientNumber": "315",
          "unitName": "MG",
          "value": 0.552,
        },
        Object {
          "nutrientId": 1089,
          "nutrientName": "Iron, Fe",
          "nutrientNumber": "303",
          "unitName": "MG",
          "value": 3.58,
        },
        Object {
          "nutrientId": 1090,
          "nutrientName": "Magnesium, Mg",
          "nutrientNumber": "304",
          "unitName": "MG",
          "value": 22,
        },
        Object {
          "nutrientId": 1091,
          "nutrientName": "Phosphorus, P",
          "nutrientNumber": "305",
          "unitName": "MG",
          "value": 303,
        },
        Object {
          "nutrientId": 1051,
          "nutrientName": "Water",
          "nutrientNumber": "255",
          "unitName": "G",
          "value": 4.7,
        },
        Object {
          "nutrientId": 1087,
          "nutrientName": "Calcium, Ca",
          "nutrientNumber": "301",
          "unitName": "MG",
          "value": 172,
        },
        Object {
          "nutrientId": 1092,
          "nutrientName": "Potassium, K",
          "nutrientNumber": "306",
          "unitName": "MG",
          "value": 114,
        },
        Object {
          "nutrientId": 1095,
          "nutrientName": "Zinc, Zn",
          "nutrientNumber": "309",
          "unitName": "MG",
          "value": 0.67,
        },
        Object {
          "nutrientId": 1212,
          "nutrientName": "Isoleucine",
          "nutrientNumber": "503",
          "unitName": "G",
          "value": 0.289,
        },
        Object {
          "nutrientId": 1213,
          "nutrientName": "Leucine",
          "nutrientNumber": "504",
          "unitName": "G",
          "value": 0.541,
        },
        Object {
          "nutrientId": 1214,
          "nutrientName": "Lysine",
          "nutrientNumber": "505",
          "unitName": "G",
          "value": 0.241,
        },
        Object {
          "nutrientId": 1216,
          "nutrientName": "Cystine",
          "nutrientNumber": "507",
          "unitName": "G",
          "value": 0.159,
        },
        Object {
          "nutrientId": 1219,
          "nutrientName": "Valine",
          "nutrientNumber": "510",
          "unitName": "G",
          "value": 0.333,
        },
        Object {
          "nutrientId": 1220,
          "nutrientName": "Arginine",
          "nutrientNumber": "511",
          "unitName": "G",
          "value": 0.307,
        },
        Object {
          "nutrientId": 1221,
          "nutrientName": "Histidine",
          "nutrientNumber": "512",
          "unitName": "G",
          "value": 0.167,
        },
        Object {
          "nutrientId": 1223,
          "nutrientName": "Aspartic acid",
          "nutrientNumber": "514",
          "unitName": "G",
          "value": 0.345,
        },
        Object {
          "nutrientId": 1227,
          "nutrientName": "Serine",
          "nutrientNumber": "518",
          "unitName": "G",
          "value": 0.399,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1277,
          "nutrientName": "MUFA 20:1",
          "nutrientNumber": "628",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1279,
          "nutrientName": "MUFA 22:1",
          "nutrientNumber": "630",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "nutrientId": 1167,
          "nutrientName": "Niacin",
          "nutrientNumber": "406",
          "unitName": "MG",
          "value": 4.43,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1062,
          "nutrientName": "Energy",
          "nutrientNumber": "268",
          "unitName": "kJ",
          "value": 1860,
        },
        Object {
          "derivationCode": "NR",
          "derivationDescription": "Nutrient that is based on other nutrient/s; value used directly, ex. Nut.#204 from Nut.#298",
          "nutrientId": 1079,
          "nutrientName": "Fiber, total dietary",
          "nutrientNumber": "291",
          "unitName": "G",
          "value": 3.4,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1275,
          "nutrientName": "MUFA 16:1",
          "nutrientNumber": "626",
          "unitName": "G",
          "value": 0.074,
        },
        Object {
          "derivationCode": "NR",
          "derivationDescription": "Nutrient that is based on other nutrient/s; value used directly, ex. Nut.#204 from Nut.#298",
          "nutrientId": 1258,
          "nutrientName": "Fatty acids, total saturated",
          "nutrientNumber": "606",
          "unitName": "G",
          "value": 2.91,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1261,
          "nutrientName": "SFA 8:0",
          "nutrientNumber": "609",
          "unitName": "G",
          "value": 0.004,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1263,
          "nutrientName": "SFA 12:0",
          "nutrientNumber": "611",
          "unitName": "G",
          "value": 0.01,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1264,
          "nutrientName": "SFA 14:0",
          "nutrientNumber": "612",
          "unitName": "G",
          "value": 0.058,
        },
        Object {
          "derivationCode": "NR",
          "derivationDescription": "Nutrient that is based on other nutrient/s; value used directly, ex. Nut.#204 from Nut.#298",
          "nutrientId": 1004,
          "nutrientName": "Total lipid (fat)",
          "nutrientNumber": "204",
          "unitName": "G",
          "value": 13.8,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1005,
          "nutrientName": "Carbohydrate, by difference",
          "nutrientNumber": "205",
          "unitName": "G",
          "value": 71.7,
        },
        Object {
          "derivationCode": "NC",
          "derivationDescription": "Calculated",
          "nutrientId": 1008,
          "nutrientName": "Energy",
          "nutrientNumber": "208",
          "unitName": "KCAL",
          "value": 446,
        },
        Object {
          "derivationCode": "NR",
          "derivationDescription": "Nutrient that is based on other nutrient/s; value used directly, ex. Nut.#204 from Nut.#298",
          "nutrientId": 2000,
          "nutrientName": "Sugars, total including NLEA",
          "nutrientNumber": "269",
          "unitName": "G",
          "value": 10.3,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1292,
          "nutrientName": "Fatty acids, total monounsaturated",
          "nutrientNumber": "645",
          "unitName": "G",
          "value": 5.48,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1293,
          "nutrientName": "Fatty acids, total polyunsaturated",
          "nutrientNumber": "646",
          "unitName": "G",
          "value": 4.87,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1259,
          "nutrientName": "SFA 4:0",
          "nutrientNumber": "607",
          "unitName": "G",
          "value": 0.014,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1260,
          "nutrientName": "SFA 6:0",
          "nutrientNumber": "608",
          "unitName": "G",
          "value": 0.004,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1262,
          "nutrientName": "SFA 10:0",
          "nutrientNumber": "610",
          "unitName": "G",
          "value": 0.009,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1265,
          "nutrientName": "SFA 16:0",
          "nutrientNumber": "613",
          "unitName": "G",
          "value": 1.44,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1266,
          "nutrientName": "SFA 18:0",
          "nutrientNumber": "614",
          "unitName": "G",
          "value": 0.673,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1268,
          "nutrientName": "MUFA 18:1",
          "nutrientNumber": "617",
          "unitName": "G",
          "value": 5.39,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1269,
          "nutrientName": "PUFA 18:2",
          "nutrientNumber": "618",
          "unitName": "G",
          "value": 4.52,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1270,
          "nutrientName": "PUFA 18:3",
          "nutrientNumber": "619",
          "unitName": "G",
          "value": 0.334,
        },
        Object {
          "derivationCode": "Z",
          "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
          "nutrientId": 1246,
          "nutrientName": "Vitamin B-12, added",
          "nutrientNumber": "578",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "derivationCode": "Z",
          "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
          "nutrientId": 1242,
          "nutrientName": "Vitamin E, added",
          "nutrientNumber": "573",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1253,
          "nutrientName": "Cholesterol",
          "nutrientNumber": "601",
          "unitName": "MG",
          "value": 11,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1162,
          "nutrientName": "Vitamin C, total ascorbic acid",
          "nutrientNumber": "401",
          "unitName": "MG",
          "value": 0.2,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1278,
          "nutrientName": "PUFA 20:5 n-3 (EPA)",
          "nutrientNumber": "629",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1178,
          "nutrientName": "Vitamin B-12",
          "nutrientNumber": "418",
          "unitName": "UG",
          "value": 0.08,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1271,
          "nutrientName": "PUFA 20:4",
          "nutrientNumber": "620",
          "unitName": "G",
          "value": 0.003,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1170,
          "nutrientName": "Pantothenic acid",
          "nutrientNumber": "410",
          "unitName": "MG",
          "value": 0.407,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1175,
          "nutrientName": "Vitamin B-6",
          "nutrientNumber": "415",
          "unitName": "MG",
          "value": 0.037,
        },
        Object {
          "derivationCode": "Z",
          "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
          "nutrientId": 1114,
          "nutrientName": "Vitamin D (D2 + D3)",
          "nutrientNumber": "328",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "derivationCode": "FLA",
          "derivationDescription": "Estimated formulation based on ingredient list; Linear program used to estimate ingredients; Analytical data",
          "nutrientId": 1103,
          "nutrientName": "Selenium, Se",
          "nutrientNumber": "317",
          "unitName": "UG",
          "value": 15.9,
        },
      ],
      "ndbNumber": 18223,
      "publishedDate": "2019-04-01",
      "score": 235.1016,
      "servingSize": 100,
    },
  ],
  "foodSearchCriteria": Object {
    "dataType": Array [
      "SR Legacy",
    ],
    "endDate": "2023-01-01",
    "pageNumber": 1,
    "pageSize": 1,
    "query": "milk",
    "requireAllWords": false,
    "startDate": "2019-01-01",
  },
  "totalHits": 211,
  "totalPages": 211,
}
`

exports[`src/__tests__/api.test.ts TAP isSearchMatch_SurveyFNDDS > isSearchMatch_SurveyFNDDS 1`] = `
Object {
  "currentPage": 1,
  "foods": Array [
    Object {
      "additionalDescriptions": "3.5% or 3.8% fat milk;leche fresca",
      "allHighlightFields": "<b>Includes</b>: 3.5% or 3.8% fat <em>milk</em>;leche fresca",
      "dataType": "Survey (FNDDS)",
      "description": "Milk, whole",
      "fdcId": 2340762,
      "foodCode": 11111000,
      "foodNutrients": Array [
        Object {
          "nutrientId": 1003,
          "nutrientName": "Protein",
          "nutrientNumber": "203",
          "unitName": "G",
          "value": 3.27,
        },
        Object {
          "nutrientId": 1004,
          "nutrientName": "Total lipid (fat)",
          "nutrientNumber": "204",
          "unitName": "G",
          "value": 3.2,
        },
        Object {
          "nutrientId": 1005,
          "nutrientName": "Carbohydrate, by difference",
          "nutrientNumber": "205",
          "unitName": "G",
          "value": 4.63,
        },
        Object {
          "nutrientId": 1008,
          "nutrientName": "Energy",
          "nutrientNumber": "208",
          "unitName": "KCAL",
          "value": 61,
        },
        Object {
          "nutrientId": 1018,
          "nutrientName": "Alcohol, ethyl",
          "nutrientNumber": "221",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "nutrientId": 1051,
          "nutrientName": "Water",
          "nutrientNumber": "255",
          "unitName": "G",
          "value": 88.1,
        },
        Object {
          "nutrientId": 1057,
          "nutrientName": "Caffeine",
          "nutrientNumber": "262",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "nutrientId": 1058,
          "nutrientName": "Theobromine",
          "nutrientNumber": "263",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "nutrientId": 2000,
          "nutrientName": "Sugars, total including NLEA",
          "nutrientNumber": "269",
          "unitName": "G",
          "value": 4.81,
        },
        Object {
          "nutrientId": 1079,
          "nutrientName": "Fiber, total dietary",
          "nutrientNumber": "291",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "nutrientId": 1087,
          "nutrientName": "Calcium, Ca",
          "nutrientNumber": "301",
          "unitName": "MG",
          "value": 123,
        },
        Object {
          "nutrientId": 1089,
          "nutrientName": "Iron, Fe",
          "nutrientNumber": "303",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "nutrientId": 1090,
          "nutrientName": "Magnesium, Mg",
          "nutrientNumber": "304",
          "unitName": "MG",
          "value": 12,
        },
        Object {
          "nutrientId": 1091,
          "nutrientName": "Phosphorus, P",
          "nutrientNumber": "305",
          "unitName": "MG",
          "value": 101,
        },
        Object {
          "nutrientId": 1092,
          "nutrientName": "Potassium, K",
          "nutrientNumber": "306",
          "unitName": "MG",
          "value": 150,
        },
        Object {
          "nutrientId": 1093,
          "nutrientName": "Sodium, Na",
          "nutrientNumber": "307",
          "unitName": "MG",
          "value": 38,
        },
        Object {
          "nutrientId": 1095,
          "nutrientName": "Zinc, Zn",
          "nutrientNumber": "309",
          "unitName": "MG",
          "value": 0.42,
        },
        Object {
          "nutrientId": 1098,
          "nutrientName": "Copper, Cu",
          "nutrientNumber": "312",
          "unitName": "MG",
          "value": 0.001,
        },
        Object {
          "nutrientId": 1103,
          "nutrientName": "Selenium, Se",
          "nutrientNumber": "317",
          "unitName": "UG",
          "value": 1.9,
        },
        Object {
          "nutrientId": 1105,
          "nutrientName": "Retinol",
          "nutrientNumber": "319",
          "unitName": "UG",
          "value": 31,
        },
        Object {
          "nutrientId": 1106,
          "nutrientName": "Vitamin A, RAE",
          "nutrientNumber": "320",
          "unitName": "UG",
          "value": 32,
        },
        Object {
          "nutrientId": 1107,
          "nutrientName": "Carotene, beta",
          "nutrientNumber": "321",
          "unitName": "UG",
          "value": 7,
        },
        Object {
          "nutrientId": 1108,
          "nutrientName": "Carotene, alpha",
          "nutrientNumber": "322",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1109,
          "nutrientName": "Vitamin E (alpha-tocopherol)",
          "nutrientNumber": "323",
          "unitName": "MG",
          "value": 0.05,
        },
        Object {
          "nutrientId": 1114,
          "nutrientName": "Vitamin D (D2 + D3)",
          "nutrientNumber": "328",
          "unitName": "UG",
          "value": 1.1,
        },
        Object {
          "nutrientId": 1120,
          "nutrientName": "Cryptoxanthin, beta",
          "nutrientNumber": "334",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1122,
          "nutrientName": "Lycopene",
          "nutrientNumber": "337",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1123,
          "nutrientName": "Lutein + zeaxanthin",
          "nutrientNumber": "338",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1162,
          "nutrientName": "Vitamin C, total ascorbic acid",
          "nutrientNumber": "401",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "nutrientId": 1165,
          "nutrientName": "Thiamin",
          "nutrientNumber": "404",
          "unitName": "MG",
          "value": 0.056,
        },
        Object {
          "nutrientId": 1166,
          "nutrientName": "Riboflavin",
          "nutrientNumber": "405",
          "unitName": "MG",
          "value": 0.138,
        },
        Object {
          "nutrientId": 1167,
          "nutrientName": "Niacin",
          "nutrientNumber": "406",
          "unitName": "MG",
          "value": 0.105,
        },
        Object {
          "nutrientId": 1175,
          "nutrientName": "Vitamin B-6",
          "nutrientNumber": "415",
          "unitName": "MG",
          "value": 0.061,
        },
        Object {
          "nutrientId": 1177,
          "nutrientName": "Folate, total",
          "nutrientNumber": "417",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1178,
          "nutrientName": "Vitamin B-12",
          "nutrientNumber": "418",
          "unitName": "UG",
          "value": 0.54,
        },
        Object {
          "nutrientId": 1180,
          "nutrientName": "Choline, total",
          "nutrientNumber": "421",
          "unitName": "MG",
          "value": 17.8,
        },
        Object {
          "nutrientId": 1185,
          "nutrientName": "Vitamin K (phylloquinone)",
          "nutrientNumber": "430",
          "unitName": "UG",
          "value": 0.3,
        },
        Object {
          "nutrientId": 1186,
          "nutrientName": "Folic acid",
          "nutrientNumber": "431",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1187,
          "nutrientName": "Folate, food",
          "nutrientNumber": "432",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1190,
          "nutrientName": "Folate, DFE",
          "nutrientNumber": "435",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1242,
          "nutrientName": "Vitamin E, added",
          "nutrientNumber": "573",
          "unitName": "MG",
          "value": 0,
        },
        Object {
          "nutrientId": 1246,
          "nutrientName": "Vitamin B-12, added",
          "nutrientNumber": "578",
          "unitName": "UG",
          "value": 0,
        },
        Object {
          "nutrientId": 1253,
          "nutrientName": "Cholesterol",
          "nutrientNumber": "601",
          "unitName": "MG",
          "value": 12,
        },
        Object {
          "nutrientId": 1258,
          "nutrientName": "Fatty acids, total saturated",
          "nutrientNumber": "606",
          "unitName": "G",
          "value": 1.86,
        },
        Object {
          "nutrientId": 1259,
          "nutrientName": "SFA 4:0",
          "nutrientNumber": "607",
          "unitName": "G",
          "value": 0.067,
        },
        Object {
          "nutrientId": 1260,
          "nutrientName": "SFA 6:0",
          "nutrientNumber": "608",
          "unitName": "G",
          "value": 0.054,
        },
        Object {
          "nutrientId": 1261,
          "nutrientName": "SFA 8:0",
          "nutrientNumber": "609",
          "unitName": "G",
          "value": 0.034,
        },
        Object {
          "nutrientId": 1262,
          "nutrientName": "SFA 10:0",
          "nutrientNumber": "610",
          "unitName": "G",
          "value": 0.084,
        },
        Object {
          "nutrientId": 1263,
          "nutrientName": "SFA 12:0",
          "nutrientNumber": "611",
          "unitName": "G",
          "value": 0.097,
        },
        Object {
          "nutrientId": 1264,
          "nutrientName": "SFA 14:0",
          "nutrientNumber": "612",
          "unitName": "G",
          "value": 0.303,
        },
        Object {
          "nutrientId": 1265,
          "nutrientName": "SFA 16:0",
          "nutrientNumber": "613",
          "unitName": "G",
          "value": 0.857,
        },
        Object {
          "nutrientId": 1266,
          "nutrientName": "SFA 18:0",
          "nutrientNumber": "614",
          "unitName": "G",
          "value": 0.309,
        },
        Object {
          "nutrientId": 1268,
          "nutrientName": "MUFA 18:1",
          "nutrientNumber": "617",
          "unitName": "G",
          "value": 0.694,
        },
        Object {
          "nutrientId": 1269,
          "nutrientName": "PUFA 18:2",
          "nutrientNumber": "618",
          "unitName": "G",
          "value": 0.115,
        },
        Object {
          "nutrientId": 1270,
          "nutrientName": "PUFA 18:3",
          "nutrientNumber": "619",
          "unitName": "G",
          "value": 0.013,
        },
        Object {
          "nutrientId": 1271,
          "nutrientName": "PUFA 20:4",
          "nutrientNumber": "620",
          "unitName": "G",
          "value": 0.004,
        },
        Object {
          "nutrientId": 1272,
          "nutrientName": "PUFA 22:6 n-3 (DHA)",
          "nutrientNumber": "621",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "nutrientId": 1275,
          "nutrientName": "MUFA 16:1",
          "nutrientNumber": "626",
          "unitName": "G",
          "value": 0.047,
        },
        Object {
          "nutrientId": 1276,
          "nutrientName": "PUFA 18:4",
          "nutrientNumber": "627",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "nutrientId": 1277,
          "nutrientName": "MUFA 20:1",
          "nutrientNumber": "628",
          "unitName": "G",
          "value": 0.004,
        },
        Object {
          "nutrientId": 1278,
          "nutrientName": "PUFA 20:5 n-3 (EPA)",
          "nutrientNumber": "629",
          "unitName": "G",
          "value": 0.001,
        },
        Object {
          "nutrientId": 1279,
          "nutrientName": "MUFA 22:1",
          "nutrientNumber": "630",
          "unitName": "G",
          "value": 0,
        },
        Object {
          "nutrientId": 1280,
          "nutrientName": "PUFA 22:5 n-3 (DPA)",
          "nutrientNumber": "631",
          "unitName": "G",
          "value": 0.002,
        },
        Object {
          "nutrientId": 1292,
          "nutrientName": "Fatty acids, total monounsaturated",
          "nutrientNumber": "645",
          "unitName": "G",
          "value": 0.688,
        },
        Object {
          "nutrientId": 1293,
          "nutrientName": "Fatty acids, total polyunsaturated",
          "nutrientNumber": "646",
          "unitName": "G",
          "value": 0.108,
        },
      ],
      "publishedDate": "2022-10-28",
      "score": 241.97224,
      "servingSize": 100,
    },
  ],
  "foodSearchCriteria": Object {
    "dataType": Array [
      "Survey (FNDDS)",
    ],
    "endDate": "2023-01-01",
    "pageNumber": 1,
    "pageSize": 1,
    "query": "milk",
    "requireAllWords": false,
    "startDate": "2019-01-01",
  },
  "totalHits": 283,
  "totalPages": 283,
}
`
